const Region = [
  "Addis Ababa",
  "Afar",
  "Amhara",
  "Benishangul",
  "Dire Dawa",
  "Gambela",
  "Harari",
  "Oromia",
  "Sidama",
  "Somali",
  "SNNP",
  "Tigray",
];

const ADDIS_ABABA_SUB_CITIES = [
  "Addis ketema",
  "Akaki Kality",
  "Arada",
  "Bole",
  "Gullele",
  "Kirkos",
  "Kolfe Keraniyo",
  "Lideta",
  "Nifas Silk Lafto",
  "Yeka",
  "Lemi Kura",
];

//

//
const TransactionType = [
  "Acount to Account - Internet",
  "Account to Account - Branch",
  "Cash",
  "Cheque",
  "EtSwitch",
  "RGTS",
  "Card",
  "Mobile",
  "Other",
];
const AttachmentValues = [
  "Attached",
  "Not Attached",
  "Required",
  "Not Required",
  "Not Applicable",
  "Registered",
  "Not Registered",
  "Paid",
  "Not Paid",
];

const VehicleStatus = [
  "Available",
  "Assigned",
  "Inactive",
  "Maintenance (ጋራዥ)",
  "Accident",
  "Retired",
  "Sold",
];

export type VehicleStatusType = (typeof VehicleStatus)[number];

const AssignedVehicleStatus = [
  "En Route to Origin",
  "Loading",
  "Loaded",
  "En Route to Destination",
  "Delayed",
  "Arrived at Destination",
  "Unloading",
];

const PaymentCollectionMethods = [
  "Bank Transfer",
  "Cash",
  "Telebirr",
  "Cheque",
  "CPO",
];

export {
  ADDIS_ABABA_SUB_CITIES,
  AssignedVehicleStatus,
  AttachmentValues,
  PaymentCollectionMethods,
  Region,
  TransactionType,
  VehicleStatus,
};

export const RegionTowens = [
  {
    region: "Addis Ababa",
    cities: [
      "Piassa",
      "Merkato",
      "Saris",
      "Bole",
      "CMC",
      "Gotera",
      "Stadium",
      "Mexico",
      "Arat Kilo",
      "Sidist Kilo",
      "Kolfe Keranio",
      "Lebu",
      "Megenagna",
      "Bole Bulbula",
      "Mekanisa",
      "Kera",
      "Ayat",
      "Summit",
      "Gerji",
      "Yeka",
      "Old Airport",
      "Kazanchis",
      "Leghar",
      "22",
      "24",
    ],
  },
  {
    region: "Afar",
    cities: ["Asayita (Asaita)", "Awash", "Dubti", "Logia", "Erta Ale"],
  },

  {
    region: "Amhara",
    cities: [
      "Gondar (Gonder )",
      "Bahir Dar",
      "Dessie (Desie)",
      "Debre Birhan (Debre Berhan)",
      "Debre Markos (Debre Marqos)",
      "Kombolcha (Kembolcha )",
      "Debre Tabor",
      "Weldiya",
      "Kobo",
      "Metema",
      "Azezo",
      "Bure",
      "Finote Selam",
      "Motta (Mota)",
      "Sekota (Soqota)",
      "Dangla (Dangila)",
      "Gorgora",
      "Chagni (Chagne )",
      "Debark (Debarq)",
      "Kemise (Kemisie)",
      "Wereta (Werota)",
      "Injibara",
      "Dembecha",
      "Nefas Mewcha",
      "Adet",
      "Mer Awi (Merawi)",
      "Bati",
      "Dabat",
      "Shewa Robit",
      "Tis Abay",
      "Lalibela",
      "Bichena",
      "Addis Zemen",
      "Mersa",
      "Ayikel (Chilga)",
      "Mekane Yesus",
      "Were Ilu",
      "Addi Arkay",
      "Debre Sina",
      "Dejen",
      "Debre Werk",
      "Ankober",
      "Amanuel",
    ],
  },

  {
    region: "Benishangul-Gumuz",
    cities: ["Asayita (Asaita)", "Awash", "Dubti", "Logia"],
  },

  {
    region: "Dire Dawa",
    cities: ["Dire Dawa (Dire Dewa)"],
  },
  {
    region: "Gambela",
    cities: ["Gambela"],
  },
  {
    region: "Harari",
    cities: ["Harer (Harar)"],
  },
  {
    region: "Oromia",
    cities: [
      "Adama (Nazret)",
      "Abomsa",
      "Addis Alem",
      "Alem Maya",
      "Ambo",
      "Asebe Teferi",
      "Arsi Negele",
      "Asasa",
      "Assela",
      "Babile",
      "Baco",
      "Bale Robe",
      "Bedele",
      "Bedesa",
      "Bekoji",
      "Burayu",
      "Deder",
      "Dembi Dolo",
      "Debre Zeyit",
      "Dodola",
      "Dukem",
      "Fiche",
      "Geba Guracha",
      "Gelemso",
      "Gimbi",
      "Ginde Beret",
      "Ginchi",
      "Ginir",
      "Goba",
      "Gore",
      "Guder",
      "Gutin",
      "Hagere Maryam",
      "Hirna",
      "Holeta",
      "Huruta",
      "Iteya",
      "Jima",
      "Kibre Mengist",
      "Kofele",
      "Langano",
      "Meki",
      "Mega",
      "Metehara",
      "Metu",
      "Mieso",
      "Mojo",
      "Moyale",
      "Nedjo",
      "Negele Borena",
      "Nekemte",
      "Robe",
      "Seka Chekorsa",
      "Sendafa",
      "Sebeta",
      "Shakiso",
      "Shambu",
      "Shek Hussein",
      "Shashemene",
      "Sire",
      "Sokoru",
      "Tinsae Berhan",
      "Tulu Bolo",
      "Welenchiti",
      "Wonji",
      "Yebelo",
      "Ziway",
    ],
  },
  {
    region: "Sidama",
    cities: ["Awasa (Hawassa)", "Yirga Alem", "Wondo Genet", "Chuko"],
  },
  {
    region: "Somalia",
    cities: [
      "jijiga",
      "gode",
      "dolo",
      "degehBur",
      "kebriDehar",
      "derwernache",
      "hartisheik",
      "togWajale",
      "awubere",
      "imi",
      "gewana",
      "werder",
    ],
  },
  {
    region: "South West Ethiopia People Region (SWEPR)",
    cities: ["Mizan Teferi", "Teppi", "Bonga"],
  },
  {
    region: "Southern Nations Nationalities and People (SNNPR)",
    cities: [
      "Wolayta Sodo",
      "Arba Minch",
      "Hosaena",
      "Dilla",
      "Butajira",
      "Areka",
      "Welkite",
      "Alaba Kulito",
      "Durame",
      "Boditi",
      "Hadero",
      "Sawla",
      "Wendo",
      "Jinka",
      "Shinshicho",
      "Shone",
      "Yirga Chefe",
      "Chencha",
      "Gidole",
      "Leku",
      "Konso",
      "Hagere Selam",
    ],
  },
  {
    region: "Tigray",
    cities: [
      "Mekele",
      "Adigrat",
      "Shire (Inda Silase)",
      "Aksum (Axum)",
      "Alamata",
      "Adwa",
      "Wikro (Wukro)",
      "Maychew",
      "Humera (Himora)",
      "Shiraro",
      "Korem",
      "Abiy Adi (Abi Adi)",
      "Mehoni (Mekhoni)",
      "May Cadera (May Kadera)",
    ],
  },
];
